### PR TITLE
Better interface parser

### PR DESCRIPTION
**Pull request by sbcgua**
Did some improvements to interface parser. It didn't take into account `ref to` and `table of` and `interfaces:`.

But now there is a problem - it find interfaces better and also stumbles upon cyclic references.

image

### CODE REVIEW

**Comment by larshp** [comment]
heh, yea, we have probably been lucky :)

note that REF TOs are okay if its the pure interface referenced, as it can refer to it due to the INTERFACE DEFERRED

**Comment by sbcgua** [comment]
So, do you think it should not capture REF TOs ? But it can also be `ref to zif_xxx=>yyy` ...
Unexpected problem in other words. Not sure what to do with it, at least for the moment

**Comment by larshp** [comment]
yes, "REF TO zif_bar" should be okay(dont add an edge), and "ref to zif_xxx=>yyy" must be an edge

**Comment by sbcgua** [comment]
ready. 
also disabled capitalized comments lint rule

**Comment by larshp** [comment]
@sbcgua rebase?

**Comment by sbcgua** [comment]
Done. 

OMG, it was an eternity ago ...

**Comment by larshp** [comment]
yea, sorry, I forgot about it

and I'll not be reading through the code today... but anyhow, not much of a hurry

**Comment by sbcgua** [comment]
No prob. I'm quite far from this for the moment ... too much work, too much

**Comment by larshp** [comment]
@sbcgua rebase?

**Comment by sbcgua** [comment]
strange I couldn't rebase it, but I merged main into it (and allowed changes)

**Comment by larshp** [comment]
heh, I think this change was not released until today, doesnt work with abapgit yet

**Comment by larshp** [comment]
fixed in 0.14.6

**Pull request merged**
