### PR TITLE
Support for including external files

### PR DESCRIPTION
**Pull request by sbcgua**
See README.md, I've added some doc on the topic.

### CODE REVIEW

**Comment by sbcgua** [comment]
stupid question: how I run tslint on windows ....

**Comment by sbcgua** [comment]
got it

**Comment by larshp** [comment]
What is the plan for running the un-merged ABAP code? I.e. how can I test the ABAP code without running it through abapmerge?

**Comment by sbcgua** [comment]
This is for https://github.com/larshp/abapGit/issues/374 - it is described there.

Briefly: for build it will be abapmerge who deliver the included files in-code, for complete installation it will be resource caching and/or CDN link.

**Comment by larshp** [comment]
so code could look like:

```abap
PERFORM resource_caching.
WRITE resource_cache->value.
* @@abapmerge include style.css > write '$$'.
```

and abapmerged file:
```abap
PERFORM resource_caching.
WRITE resource_cache->value.
write 'foo'.
```

how will the resource_caching be disabled/enabled? How will a typical solution look like?

**Comment by sbcgua** [comment]
No. There will some class, let's say `resource_crawler`
And let's say there will be some method `resource_crawler->get_resource(id)` - set of id's is in fact known and limited.

So it will do something like (pseudo code)

```abap
method get_resource.
...
  if (id = 'css').
   lv_result =  css_in_code().
   if lv_result is initial.
    lv_result = get_resource_somewhere_else()
   endif.
endmethod.

method css_in_code.
  data tab type table of string. 
  "@@abapmerge include style.css > APPEND '$$' TO tab.
  rv_result = concat_lines_of( table = tab, sep =  `\n` ).
endmethod.
```

**Comment by larshp** [comment]
ok, any thoughts on how to handle branching? The ABAP code does know know where its source is stored or which branch it is part of

**Comment by sbcgua** [comment]
haven't thought about this much yet. this is a good question. But general idea is that css/js will be a part of repo (assets folder or similar). So it will be non-code file which in fact is processed by abapGit. So css/js should not be just skipped but stored to DB instead. Thus it will be in line with current branch. Maybe it should be mentioned in `.abapGit` for that. Or maybe not, as actually assets for abapGit are known and can be hardcoded.

**Comment by larshp** [comment]
idea: store the css/js as mime objects in the SAP system, these can then be part of the git repository, and abapmerge can include them.

eg. like https://github.com/larshp/abapGitServer/blob/master/src/frontend/02c1f55747191ed58ab0401507578067.smim.index.html is a SMIM object, part of the git repository and stored as an object in the SAP system

**Comment by sbcgua** [comment]
I was actually planning to use W3MI back in 374 :) But yes, thats the idea.
Now a stupid question: whats the difference between SMIM and W3MI ? I haven't used SMIM before :(

**Comment by sbcgua** [comment]
I sorry I've got you. You mean storing the asset as a part of repo instead of getting it separately by resource_crawler ?

**Comment by larshp** [comment]
yes, storing it as part of the repo

W3MI vs SMIM: not sure, might be better with W3MI, as I do not like the keys/names of the SMIM files

**Comment by sbcgua** [comment]
Current thoughts:
- SMIM looks better because it stores actual text in repo. W3MI is base64ed.
- maybe ... serailization can be changed for W3MI ... as an idea ... not sure if it will work for all non-abapGit cases
- naming in SMIM - is it GUID ? Is it possible to change naming in serialization somehow ? (also not sure)
- there is still always a way to specially handle abapGit non-code files.

anyway some experiments to do.

**Comment by larshp** [comment]
I'm quite busy with real work stuff, will get back to this by end of this week.

**Comment by larshp** [comment]
lets do it, thanks!

**Comment by larshp** [comment]
v0.6.0 published to NPM

If you start working on integrating into abapGit please make a simple/small PR first, so we can agree on the setup, before spending a lot of time separating into .css and .png files

**Pull request merged**
